-- Shared candidate message thread for recruiter / HM / interviewer / inbox.
-- Run in the Supabase SQL editor after notifications.sql.

create table if not exists public.application_messages (
  id bigint generated by default as identity primary key,
  application_id bigint not null references public.applications (id) on delete cascade,
  company_id bigint not null,
  sent_by uuid references auth.users (id) on delete set null,
  template_key text,
  subject text not null,
  body text not null,
  email_sent boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists application_messages_application_id_idx
  on public.application_messages (application_id, created_at desc);

alter table public.application_messages enable row level security;

drop policy if exists application_messages_select_company on public.application_messages;
create policy application_messages_select_company
  on public.application_messages for select
  using (
    exists (
      select 1
      from public.company_members cm
      where cm.user_id = auth.uid()
        and cm.company_id = application_messages.company_id
    )
  );
