-- Full schema. Needs CREATE on public (role postgres / supabase_admin).
-- If CREATE fails with "permission denied for schema public", run
-- assessment-jsonb-fallback.sql instead (ALTER existing tables only).

create table if not exists public.coding_assessments (
  id bigint generated by default as identity primary key,
  job_id bigint not null,
  company_id bigint not null,
  title text not null,
  description text,
  duration_minutes int not null default 60,
  pass_score numeric default 60,
  max_violations int not null default 3,
  questions jsonb not null default '[]'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now()
);

create table if not exists public.assessment_attempts (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.coding_assessments(id) on delete cascade,
  application_id bigint,
  candidate_id bigint not null,
  status text not null default 'assigned',
  started_at timestamptz,
  submitted_at timestamptz,
  score numeric,
  max_score numeric,
  violation_count int not null default 0,
  plagiarism_flag boolean not null default false,
  answers_json jsonb not null default '{}'::jsonb,
  violations_json jsonb not null default '[]'::jsonb,
  question_order jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists assessment_attempts_assessment_application_uidx
  on public.assessment_attempts (assessment_id, application_id)
  where application_id is not null;

create index if not exists assessment_attempts_candidate_idx
  on public.assessment_attempts (candidate_id);

alter table public.coding_assessments
  add column if not exists questions jsonb default '[]'::jsonb,
  add column if not exists pass_score numeric default 60,
  add column if not exists max_violations int default 3,
  add column if not exists description text,
  add column if not exists updated_at timestamptz default now();

alter table public.assessment_attempts
  add column if not exists answers_json jsonb default '{}'::jsonb,
  add column if not exists violations_json jsonb default '[]'::jsonb,
  add column if not exists question_order jsonb default '[]'::jsonb,
  add column if not exists max_score numeric,
  add column if not exists violation_count int default 0,
  add column if not exists plagiarism_flag boolean default false,
  add column if not exists application_id bigint;

select 'ok: coding assessment tables ready' as status;
